import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`font-sans antialiased`}
      >
        <div className="min-h-screen mx-auto max-w-8xl px-10">
          <div className="min-h-screen mx-auto py-5 flex flex-row">
            <header className="h-screen w-1/4"></header>
            <section className="w-full h-inherit flex flex-col px-3">
              <Nav/>
              {children}
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}
