import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav";
import Header from "@/components/header";
// Tambahkan import contact di sini
// import ContactPage from "@/components/ContactPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`font-sans antialiased`}
      >
        <div className="min-h-screen mx-auto max-w-8xl px-10">
          <div className="min-h-screen mx-auto py-10 flex flex-row">
            <header className="h-screen w-1/4">
              <Header/>
            </header>
            <section className="w-full h-inherit flex flex-col px-3">
              <Nav/>
              {children}
              {/* Tambahkan komponen Contact di sini agar muncul di bawah konten utama */}
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}