import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Nav from "@/components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen mx-auto max-w-8xl px-10">
          <div className="min-h-screen mx-auto py-5 flex flex-row">
            <header className="h-screen w-1/4"></header>
            <section className="w-full h-inherit flex flex-col px-3">
              <Nav/>
              {children}
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}
